<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NeutralLanguage>en-US</NeutralLanguage>
    <TargetFrameworks>net6.0</TargetFrameworks>
    <AssemblyOriginatorKeyFile>Jint.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
    <LangVersion>latest</LangVersion>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net6.0|AnyCPU'">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net6.0|AnyCPU'">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\esprima\src\Esprima\Esprima.csproj" />
  </ItemGroup>
</Project>
